export const featureNames = [
  "members",
  "memberships",
  "trainers",
  "staff",
  "attendance",
  "payments",
  "reports",
  "expenses",
  "analytics",
  "whatsapp_chat",
  "automated_whatsapp",
  "member_portal",
  "member_workouts",
  "workouts",
  "progress",
  "leads",
  "appointments",
  "inventory",
  "backup",
  "branding",
  "api",
  "branches",
  "ai",
] as const;
export const limitNames = [
  "member",
  "staff",
  "TRAINER",
  "RECEPTIONIST",
  "MANAGER",
] as const;
export const ownerPermissionNames = [
  "members:read",
  "members:create",
  "members:edit",
  "members:deactivate",
  "members:account",
] as const;
export const staffPermissionNames = [
  "dashboard",
  "members:read",
  "members:create",
  "members:edit",
  "members:deactivate",
  "members:account",
  "memberships",
  "payments",
  "attendance",
  "reports",
  "trainers",
  "workouts",
  "progress",
  "leads",
  "appointments",
  "inventory",
  "notifications",
  "whatsapp",
  "assigned:read",
] as const;
export const permissionFeature: Record<string, string> = {
  "members:read": "members",
  "members:create": "members",
  "members:edit": "members",
  "members:deactivate": "members",
  "members:account": "member_portal",
  "members:write": "members",
  memberships: "memberships",
  payments: "payments",
  attendance: "attendance",
  reports: "reports",
  staff: "staff",
  trainers: "trainers",
  workouts: "workouts",
  progress: "progress",
  leads: "leads",
  appointments: "appointments",
  inventory: "inventory",
  backup: "backup",
  expenses: "expenses",
  "assigned:read": "trainers",
  "self:read": "member_portal",
  whatsapp: "whatsapp_chat",
};
